### ISSUE TITLE
missing APKs on f-droid

### ISSUE THREAD

**Issue by ArneBab** [louboco/Icicle#3]
Hi,

The APK download links on f-droid are broken: https://f-droid.org/packages/co.loubo.icicle/ → https://f-droid.org/repo/co.loubo.icicle_4.apk

Best wishes,  
Arne

**Comment by louboco** [comment]
Thanks for the heads up. I've bumped the version to see if that causes Fdroid to re-create a new APK.

**Comment by ArneBab** [comment]
Thank you!

**Comment by louboco** [comment]
I see now where you can download the latest version. I was looking for version 5 to show up the way version 4 does. It looks like old versions are unavailable. Closing issue. Thanks again for the report.
